name: Aliasmanager CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set Nx git references
        uses: nrwl/nx-set-shas@v3
      - name: Install dependencies
        run: pnpm install
      - name: Run build of affected packages
        run: pnpm nx affected --target=build --parallel=3
